name: Build

on: [pull_request, push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.2

            -   uses: actions/checkout@v1

            -   name: Validate composer.json and composer.lock
                run: |
                    composer clear-cache
                    composer validate

            -   name: Install dependencies
                run: |
                    composer install --prefer-dist --no-progress --no-suggest

            -   name: Upload artifact
                uses: actions/upload-artifact@v2
                with:
                    name: build
                    path: ./

    psalm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Download build
                uses: actions/download-artifact@v2
                with:
                    name: build
            -   name: Psalm
                run: |
                    composer run psalm

    php_stan:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Download build
                uses: actions/download-artifact@v2
                with:
                    name: build
            -   name: PHP Stan
                run: |
                    composer run phpstan

    php_unit:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Download build
                uses: actions/download-artifact@v2
                with:
                    name: build
            -   name: PHP Unit
                run: |
                    composer run phpunit
